---
- hosts: localhost
  become: yes
  tasks:
    - name: install docker and docker-compose
      apt:
        pkg:
          - docker.io
          - docker-compose
        state: latest
        update_cache: yes
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '12' or ansible_distribution == 'Ubuntu' and ansible_distribution_version == '22.04'
